### ISSUE TITLE
nur Buchstaben in Namen der Musterdatensätze

### ISSUE THREAD

**Issue by jze** [bertelsmannstift/Musterdatenkatalog#13]
Die Namen einiger weniger Musterdatensätze enthalten Komma und Schrägstrich:

- Grünflächen - Grünflächen/Grünflächenkataster
- Grünflächen - Baumbestand/Baumkataster
- Externe Infrastruktur - Kirchen, Kapellen und Klöster
- Vereine, Verbände - Einrichtungen

Beide Zeichen sorgen bei Webanwendungen Schwierigkeiten. Mit dem Komma werden üblicherweise die Schlagworte getrennt und der Schrägstrich wird in Webadressen gerene als Verzeichnistrenner interpretiert. Ich schlage daher folgende Ersetzungen vor.

- Grünflächen - Grünflächenkataster
- Grünflächen - Baumkataster
- Externe Infrastruktur - Kirchen Kapellen Klöster
- Vereine und Verbände - Einrichtungen

**Comment by mariosorg** [comment]
Vielen Dank für die Vorschläge! Wir prüfen sie im Rahmen einer in den kommenden Wochen anstehenden Weiterentwicklung des Musterdatenkatalogs.

**Comment by mariosorg** [comment]
Danke für die Anregungen. Diese Antwort hat leider etwas auf sich warten lassen aber Du hattest durch Dein Mitwirken an der Weiterentwicklung des Musterdatenkatalogs ja dann mitbekommen, dass wir daran arbeiten. In der kürzlich veröffentlichten und weiterentwickelten Version 4 des Musterdatenkatalogs gibt es die Kommas und Schrägstriche nicht mehr.
