### ISSUE TITLE
unklarer Musterdatensatz bei Haushalt

### ISSUE THREAD

**Issue by jze** [bertelsmannstift/Musterdatenkatalog#14]
Den [Datensatz Haushalt der Stadt Glücksburg](https://opendata.schleswig-holstein.de/dataset/glueckstadt-haushalt-2021) kann ich nur schwer einem Musterdatensatz zuordnen, da mehrere Musterdatensätze aus dem Thema "Haushalt" in Frage kommen. Laut der Beschreibung des Datensatzes ist enthalten:

- Ergebnis Jahresabschluss
- Haushaltsansatz
- Mittelfristige Finanzplanung

In Frage kommen für mich folgende Musterdatensätze: 
- [Ergebnisplan](https://musterdatenkatalog.de/def/musterdatensatz/haushalt/ergebnisplan)
- [Finanzplan](https://musterdatenkatalog.de/def/musterdatensatz/haushalt/finanzplan)
- [Haushaltsplan](https://musterdatenkatalog.de/def/musterdatensatz/haushalt/haushaltsplan)
- [Jahresabschluss](https://musterdatenkatalog.de/def/musterdatensatz/haushalt/jahresabschluss)

Welcher Musterdatensatz ist der richtig?

**Comment by mariosorg** [comment]
Bei Haushaltsdaten fällt die Zuordnung häufig schwer, weil sie von den Kommunen auf unterschiedliche Art und Weise veröffentlicht werden. Unter "Jahresabschluss" gibt es aktuell nur einen Datensatz. Es kann gut sein, dass dieser Musterdatensatz in einer Weiterentwicklung des Musterdatenkatalogs herausfällt, weil er nicht genutzt wird. Vergleichbare Datensätze zu dem aus Glücksburg finden sich unter "Haushaltsplan". Eine Einordnung des Glücksburger Datensatzes macht hier vermutlich am meisten Sinn.

**Comment by mariosorg** [comment]
Bei Haushaltsdaten fällt die Zuordnung häufig schwer, weil sie von den Kommunen auf unterschiedliche Art und Weise veröffentlicht werden. Unter "Jahresabschluss" gibt es aktuell nur einen Datensatz. Es kann gut sein, dass dieser Musterdatensatz in einer Weiterentwicklung des Musterdatenkatalogs herausfällt, weil er nicht genutzt wird. Vergleichbare Datensätze zu dem aus Glücksburg finden sich unter "Haushaltsplan". Eine Einordnung des Glücksburger Datensatzes macht hier vermutlich am meisten Sinn.
